### ISSUE TITLE
What is the use case?

### ISSUE THREAD

**Issue by diimdeep** [iainmckay/docker-phpstorm#15]
Hi,

What is use case for running phpStorm inside Docker ?

**Comment by iainmckay** [comment]
For myself, at the time, I was moving development machines frequently. This was an exercise in isolating my development environment and the dependencies required so that when I moved machine I was only a couple of `docker pull` away being up and running.

I find I don't really use this container now that I don't move between machines very often.

I can't answer for the other people that use this image, it's been pulled over 1.2k times now (I'm probably 1,119 of those) but they must have their own reasons.

**Comment by germainpigeon** [comment]
Hi, it is a bit late but I feel like the answer remains incomplete.

My personnal use case in forking this repository is to create a Dockerfile for Windows and OSX with the ability to access PHP files in a Docker volume (driver=local).

The story behing this is that folders in Windows and OSX are mounted in Linux containers via CIFS. With a large repository (500+ file) comes a network overhead that slows down file accesses. On a Debian host there is almost no difference (shared ext4 I guess).

Example : "time git status" from the container
- Debian host ; 20ms
 - Windows host : 1000s
 - OSX host : 2000s

There is almost no alternative in Windows, I tried to reverse the share (PHPStorm on the host accessing files in the container) or to mount a shared VHDX with no luck.

Having PHPStorm in a container and setting up an X Server on the host is the closest to a perfect solution...

Thank you for your work !
